### ISSUE TITLE
Cycling animations when none are available causes a crash

### ISSUE THREAD

**Issue by amclain** [ElixirSeattle/xebow#112]
## Description

If all of the animations are disabled, attempting to cycle to the next/previous animation causes a crash. Based on the error message, it appears that the config is trying to be retrieved for a non-existent animation.

```text
** (UndefinedFunctionError) function nil.config/0 is undefined
    nil.config()
    (xebow 0.1.0) lib/rgb_matrix/animation.ex:105: RGBMatrix.Animation.get_config/1
```

## Expected behavior

Nothing happens when attempting to cycle the animation (no-op).

## Steps to reproduce

Disable all active animations on the animations page.

![image](https://user-images.githubusercontent.com/4755047/89719717-251e3780-d980-11ea-9350-74310a80a1c1.png)

Navigate back to the dashboard and cycle to the next or previous animation.

![image](https://user-images.githubusercontent.com/4755047/89719711-0ae45980-d980-11ea-972b-539a6885bfd0.png)

The following error is printed in the console.

```text
[error] GenServer RGBMatrix.Engine terminating
** (UndefinedFunctionError) function nil.config/0 is undefined
    nil.config()
    (xebow 0.1.0) lib/rgb_matrix/animation.ex:105: RGBMatrix.Animation.get_config/1
    (xebow 0.1.0) lib/rgb_matrix/engine.ex:233: RGBMatrix.Engine.inform_configurables/1
    (xebow 0.1.0) lib/rgb_matrix/engine.ex:182: RGBMatrix.Engine.handle_cast/2
    (stdlib 3.13) gen_server.erl:680: :gen_server.try_dispatch/4
    (stdlib 3.13) gen_server.erl:756: :gen_server.handle_msg/6
    (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:set_animation, nil}}
State: %RGBMatrix.Engine.State{animation: %RGBMatrix.Animation{config:
%RGBMatrix.Animation.SolidReactive.Config{direction: :random, distance: 180,
speed: 4}, state: %RGBMatrix.Animation.SolidReactive.State{color:
%Chameleon.HSV{h: 190, s: 100, v: 100}, first_render: false, hits: %{}, leds:
[%Layout.LED{id: :l001, x: 0, y: 0}, %Layout.LED{id: :l002, x: 1, y: 0},
%Layout.LED{id: :l003, x: 2, y: 0}, %Layout.LED{id: :l004, x: 0, y: 1},
%Layout.LED{id: :l005, x: 1, y: 1}, %Layout.LED{id: :l006, x: 2, y: 1},
%Layout.LED{id: :l007, x: 0, y: 2}, %Layout.LED{id: :l008, x: 1, y: 2},
%Layout.LED{id: :l009, x: 2, y: 2}, %Layout.LED{id: :l010, x: 0, y: 3},
%Layout.LED{id: :l011, x: 1, y: 3}, %Layout.LED{id: :l012, x: 2, y: 3}],
paused: true, tick: 0}, type: RGBMatrix.Animation.SolidReactive}, configurables:
#MapSet<[#Function<5.66497960/1 in XebowWeb.MatrixLive.register_with_engine!/0>]>,
last_frame: %{l001: %Chameleon.HSV{h: 190, s: 100, v: 100},
l002: %Chameleon.HSV{h: 190, s: 100, v: 100}, l003: %Chameleon.HSV{h: 190, s: 100, v: 100},
l004: %Chameleon.HSV{h: 190, s: 100, v: 100}, l005: %Chameleon.HSV{h: 190, s: 100, v: 100},
l006: %Chameleon.HSV{h: 190, s: 100, v: 100}, l007: %Chameleon.HSV{h: 190, s: 100, v: 100},
l008: %Chameleon.HSV{h: 190, s: 100, v: 100}, l009: %Chameleon.HSV{h: 190, s: 100, v: 100},
l010: %Chameleon.HSV{h: 190, s: 100, v: 100}, l011: %Chameleon.HSV{h: 190, s: 100, v: 100},
l012: %Chameleon.HSV{h: 190, s: 100, v: 100}}, leds: [%Layout.LED{id: :l001, x: 0, y: 0},
%Layout.LED{id: :l002, x: 1, y: 0}, %Layout.LED{id: :l003, x: 2, y: 0},
%Layout.LED{id: :l004, x: 0, y: 1}, %Layout.LED{id: :l005, x: 1, y: 1},
%Layout.LED{id: :l006, x: 2, y: 1}, %Layout.LED{id: :l007, x: 0, y: 2},
%Layout.LED{id: :l008, x: 1, y: 2}, %Layout.LED{id: :l009, x: 2, y: 2},
%Layout.LED{id: :l010, x: 0, y: 3}, %Layout.LED{id: :l011, x: 1, y: 3},
%Layout.LED{id: :l012, x: 2, y: 3}], paintables:
#MapSet<[#Function<4.66497960/1 in XebowWeb.MatrixLive.register_with_engine!/0>]>,
timer: nil}
```

**Comment by vanvoljg** [comment]
I've got a fix ready for this. Do you want me to push the branch and make a PR before or after you get #109 merged?

**Comment by amclain** [comment]
After #109 is probably best since that PR is ultimately going to expose the issue. Probably fewer conflicts to resolve that way.
